### ISSUE TITLE
I can't docker-compose this docker

### ISSUE THREAD

**Issue by Giagoo** [xthursdayx/yacreaderlibrary-server-docker#44]
The steps are repeated
1. docker pull ghcr.io/xthursdayx/yacreaderlibrary-server-docker:p7zip
![image](https://github.com/xthursdayx/yacreaderlibrary-server-docker/assets/41316613/02168afc-8d19-4f5f-a6f8-ee9d6d2ef039)
2.Creat docker-compose.yml
![image](https://github.com/xthursdayx/yacreaderlibrary-server-docker/assets/41316613/9fa12067-3981-4ae7-b065-b4f41a41744c)
3.docker-compose up -d
![image](https://github.com/xthursdayx/yacreaderlibrary-server-docker/assets/41316613/a01bb3b3-57da-457e-961e-a4b330556016)
but, It doesn't work,Isn't that how it works? by the way , my system is here
![image](https://github.com/xthursdayx/yacreaderlibrary-server-docker/assets/41316613/bf1167b5-238e-4bbd-bc14-2ea4d328456a)

**Comment by xthursdayx** [comment]
Try editing the tag in your docker-compose file to be p7zip, rather than [p7zip]:
```
---
version: "3"
services:
  yacreaderlibrary-server-docker:
    container_name: YACReaderLibraryServer
    image: xthursdayx/yacreaderlibrary-server-docker:p7zip
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /path/to/config:/config
      - /path/to/comics:/comics
    ports:
      - 8080:8080
    restart: unless-stopped
```
