### ISSUE TITLE
[BUG] iOS import not working

### ISSUE THREAD

**Issue by xavier7179** [xthursdayx/yacreaderlibrary-server-docker#52]
Trying to synch the iOS app through server connection but, after browsing, importing gives an error ("There were errors during the import process, check your files and/or network connectivity - error: Error retrieving comic pages, HTTP: 404") that seems to correspond to the following lines on logs:

```
WARN  2023-10-07T08:16:10.431 QObject: Cannot create children for a parent that is in a different thread.
(Parent is RequestMapper(0x557971038f30), parent's thread is QThread(0x55797102e4f0), current thread is QThread(0x557971042470)
INFO  2023-10-07T08:16:27.639 YACReaderLibrary closed with exit code : 700
INFO  2023-10-07T08:16:27.662 YACReaderLibraryServer attempting to start
```

------------------------------

## Expected Behavior
Sync perfectly working

## Current Behavior
Sync is not working at all

## Environment
**OS: Ubuntu 20.04.6 LTS

## Command used to create docker container (run/create/compose/screenshot)
```
yacserver:
      image: xthursdayx/yacreaderlibrary-server-docker:p7zip
      container_name: yacserver
      restart: always
      networks:
         t2_proxy:
            ipv4_address: $YACSERVER_T2_IP
      security_opt:
         - no-new-privileges:true
      environment:
         PUID: $PUID
         PGID: $PGID
         TZ: $TZ
      ports:
         - "$YACSERVER_PORT:8080"
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - $DOCKERDIR/yacserver/config:/config
         - $MEDIADIR/comics:/comics
```
## Docker logs (QR code omitted)
```
----------------------------------------------------------
   _  __________  ____  ______  _____ ____  _____  ___  __
  | |/ /_  __/ / / / / / / __ \/ ___// __ \/   \ \/ / |/ /
  |   / / / / /_/ / / / / /_/ /\__ \/ / / / /| |\  /|   /
 /   | / / / __  / /_/ / _, _/___/ / /_/ / ___ |/ //   |
/_/|_|/_/ /_/ /_/\____/_/ |_|/____/_____/_/  |_/_//_/|_|

Brought to you by xthursdayx
----------------------------------------------------------
GID/UID
----------------------------------------------------------

User uid:    1000
User gid:    1001
-------------------------------------

[custom-init] No custom files found, skipping...
INFO  2023-10-07T08:14:57.651 YACReaderLibraryServer attempting to start
INFO  2023-10-07T08:14:57.651 ---------- System & configuration ----------
INFO  2023-10-07T08:14:57.651 OS: "Ubuntu 22.04.2 LTS" Version:  "22.04"
INFO  2023-10-07T08:14:57.651 Kernel: "linux" "5.4.0-164-generic" Architecture: "x86_64"
INFO  2023-10-07T08:14:57.652 Libraries:  QMap(("comics", QPair(1,"/comics")))
INFO  2023-10-07T08:14:57.652 --------------------------------------------
INFO  2023-10-07T08:14:57.656 YACReaderLibrary starting
INFO  2023-10-07T08:14:57.660 Running on "192.168.17.112:8080"

[ls.io-init] done.
WARN  2023-10-07T08:16:10.281 QObject: Cannot create children for a parent that is in a different thread.
(Parent is RequestMapper(0x561578de6f30), parent's thread is QThread(0x561578ddc4f0), current thread is QThread(0x561578df0e80)
INFO  2023-10-07T08:16:10.308 YACReaderLibrary closed with exit code : 700
INFO  2023-10-07T08:16:10.368 YACReaderLibraryServer attempting to start
INFO  2023-10-07T08:16:10.368 ---------- System & configuration ----------
INFO  2023-10-07T08:16:10.368 OS: "Ubuntu 22.04.2 LTS" Version:  "22.04"
INFO  2023-10-07T08:16:10.368 Kernel: "linux" "5.4.0-164-generic" Architecture: "x86_64"
INFO  2023-10-07T08:16:10.369 Libraries:  QMap(("comics", QPair(1,"/comics")))
INFO  2023-10-07T08:16:10.369 --------------------------------------------
INFO  2023-10-07T08:16:10.369 YACReaderLibrary starting
INFO  2023-10-07T08:16:10.370 Running on "192.168.17.112:8080"


WARN  2023-10-07T08:16:10.431 QObject: Cannot create children for a parent that is in a different thread.
(Parent is RequestMapper(0x557971038f30), parent's thread is QThread(0x55797102e4f0), current thread is QThread(0x557971042470)
INFO  2023-10-07T08:16:27.639 YACReaderLibrary closed with exit code : 700
INFO  2023-10-07T08:16:27.662 YACReaderLibraryServer attempting to start
INFO  2023-10-07T08:16:27.662 ---------- System & configuration ----------
INFO  2023-10-07T08:16:27.662 OS: "Ubuntu 22.04.2 LTS" Version:  "22.04"
INFO  2023-10-07T08:16:27.662 Kernel: "linux" "5.4.0-164-generic" Architecture: "x86_64"
INFO  2023-10-07T08:16:27.662 Libraries:  QMap(("comics", QPair(1,"/comics")))
INFO  2023-10-07T08:16:27.662 --------------------------------------------
INFO  2023-10-07T08:16:27.663 YACReaderLibrary starting
INFO  2023-10-07T08:16:27.663 Running on "192.168.17.112:8080"


WARN  2023-10-07T08:16:27.760 QObject: Cannot create children for a parent that is in a different thread.
(Parent is RequestMapper(0x55bac1a0cf30), parent's thread is QThread(0x55bac1a024f0), current thread is QThread(0x55bac1a15530)
