### ISSUE TITLE
[BUG] Only the first of multiple libraries can be browsed

### ISSUE THREAD

**Issue by j-syn** [xthursdayx/yacreaderlibrary-server-docker#53]
------------------------------

## Expected Behavior
I should be able to add multiple libraries and browse all of them. 

## Current Behavior
Currently, if you add multiple libraries they will all be displayed on your YACReaderLibraryServer homepage, but only the first one can be browsed. Clicking the others does nothing. Whichever library is listed first when you type `YACReaderLibraryServer list-libraries` is the only library that will work. Removing this library then allows you to browse the next one, since it is now the first library in the list.

## Steps to Reproduce
1. Create multiple libraries. e.g.:
```
YACReaderLibraryServer add-library "Comic Books and Graphic Novels" /comics
YACReaderLibraryServer add-library "Comic Strip Collections" /funnypages
YACReaderLibraryServer add-library "Magazines" /magazines
```
2. Now browse to your YacReaderLibraryServer homepage. All three libraries are listed, in the order they were added.
3. Click on the first Library in the list. You will be able to browse the comic books within, no problem.
4. Click on the other Libraries in the list. Clicking them will do nothing. You can not browse them.
5. Now delete the first Library. e.g.:
```
YACReaderLibraryServer remove-library "Comic Books and Graphic Novels"
```
6. Now browse to your YACReaderLibraryServer homepage. Only the two remaining libraries are listed, still in the order they were first added.
7. Click on the first Library in the list. It did not used to be the first Library in the list, and you could not browse it. But it is now the first Library in the list. You can now browse the comic books within, no problem.
8. Click on the next Library in the list. Clicking it will do nothing. You can not browse it

## Environment
This was done on Synology, using the fix [described here](https://github.com/xthursdayx/yacreaderlibrary-server-docker/issues/39#issuecomment-1796418412)

## Command used to create docker container (run/create/compose/screenshot)
```
version: "3"
services:
  image: xthursdayx/yacreaderlibrary-server-docker:unarr
  container_name: YACReaderLibraryServer
  healthcheck:
    test: curl -f http://localhost:8080/ || exit 1
  mem_limit: 4g
  cpu_shares: 192
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  ports: 
    - 8080:8080
  volumes:
    - "/volume1/docker/yaclibraryserver:/config"
    - "/volume1/music/My Media/Comics and Comic Strips/Comics Sorted:/comics"
    - "/volum1/music/My Media/Comics and Comic Strips/Comic Strip Collections:/funnypages"
    - "/volume1/music/My Media/Magazines:/magazines"
  environment:
    PUID: 1024
    PGID: 100
    TZ: America/New_York
```

Followed by:
```
apt-get update
apt-get install binutils
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
YACReaderLibraryServer add-library "Comic Books and Graphic Novels" /comics
YACReaderLibraryServer add-library "Comic Strip Collections" /funnypages
YACReaderLibraryServer add-library "Magazines" /magazines
```

All volumes and directories are populated with comic books and are readable. All volumes have worked with other YACReaderLibraryServer docker images in the past (e.g. Mullion/yacreaderlibraryserver). All volumes and Libraries work great if they are actively the top Library on the homepage. Forcibly removing and adding the Libraries to change the order they are in prove that they all work, provided they are the first Library in the list. Thus, this does not appear to be a permissions problem.

Is this a Synology-specific bug or something related to this package? Has anyone else gotten multiple libraries to work in the current version?
